# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionimagedata'),
        ('users', '0002_auto_20170907_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionData')),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='last_question_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestiondata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserData'),
        ),
    ]
