# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170907_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='last_question_answered',
            field=models.ForeignKey(blank=True, db_column='question_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionData'),
        ),
    ]
