# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170913_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='last_question_answered',
            field=models.IntegerField(default=0),
        ),
    ]
