# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userbonusquestiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbonusquestiondata',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.BonusQuestionData'),
        ),
    ]
