# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionimagedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
