# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170907_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionHints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(blank=True, max_length=1000, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionData')),
            ],
        ),
        migrations.CreateModel(
            name='StoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=3000, null=True)),
                ('image', models.ImageField(blank=True, upload_to='/media/')),
            ],
        ),
    ]
