# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170912_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusQuestionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('question_no', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
