# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_bonusquestiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusquestiondata',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/bonus_questions/'),
        ),
    ]
